# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Project/Xilinx_Vivado/Camera_Demo/Camera_Demo.srcs/sources_1/ip/RAM_Line/RAM_Line.xci
# IP: The module: 'RAM_Line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Xilinx_Vivado/Camera_Demo/Camera_Demo.srcs/sources_1/ip/RAM_Line/RAM_Line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_Line'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Project/Xilinx_Vivado/Camera_Demo/Camera_Demo.srcs/sources_1/ip/RAM_Line/RAM_Line.xci
# IP: The module: 'RAM_Line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Xilinx_Vivado/Camera_Demo/Camera_Demo.srcs/sources_1/ip/RAM_Line/RAM_Line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_Line'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
